# .github/workflows/publish.yml
name: publish

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+' # for tags like: 'v1.2.3'

jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # or 'beta', 'dev'
      - uses: dart-lang/setup-dart@v1 
      - name: Install dependencies
        run: flutter pub get
      - name: generate build_runner
        run: dart run build_runner build -d      
      - name: Publish dryrun
        run: dart pub publish --dry-run
      - name: Publish
        run: dart pub publish --force
