# .github/workflows/publish.yml
name: publish

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+' # for tags like: 'v1.2.3'

jobs:
  build_runner:
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.4'
      - name: Install dependencies
        run: flutter pub get
      - name: generate build_runner
        run: dart run build_runner build -d
  publish:
    needs: build_runner
    permissions:
      id-token: write # Required for authentication using OIDC
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    # with:
      # Specify the github actions deployment environment
      # environment: pub.dev
      # working-directory: path/to/package/within/repository  
